COUNTIES = {
    "abbeville",
    "aiken",
    "allendale",
    "anderson",
    "bamberg",
    "barnwell",
    "beaufort",
    "berkeley",
    "calhoun",
    "charleston",
    "cherokee",
    "chester",
    "chesterfield",
    "clarendon",
    "colleton",
    "darlington",
    "dillon",
    "dorchester",
    "edgefield",
    "fairfield",
    "florence",
    "georgetown",
    "greenville",
    "greenwood",
    "hampton",
    "horry",
    "jasper",
    "kershaw",
    "lancaster",
    "laurens",
    "lee",
    "lexington",
    "marion",
    "marlboro",
    "mcCormick",
    "newberry",
    "oconee",
    "orangeburg",
    "pickens",
    "richland",
    "saluda",
    "spartanburg",
    "sumter",
    "union",
    "williamsburg",
    "york"
}

YEARS = {
    1991,
    1992,
    1993,
    1994,
    1995,
    1996,
    1997,
    1998,
    1999,
    2000,
    2002,
    2003,
    2004,
    2005,
    2006,
    2007,
    2008,
    2009,
    2010,
    2011,
    2012,
    2013,
    2014,
    2015,
    2016,
    2017,
    2018,
    2019,
    2020,
    2021
}

CRIMES = {
    "kidnapping": "Kidnapping/Abduction",
    "shoplifting": "Shoplifting",
    "vandalism": "Destruction/Damage/Vandalism of Property",
    "theft-from-vehicle": "Theft From Motor Vehicle",
    "gta": "Motor Vehicle Theft",
    "theft-from-building": "Theft From Building",
    "sexual-exposure": "Sexual Exposure",
    "statutory-rape": "Statutory Rape",
    "murder": "Murder and Nonnegligent Manslaughter",
    "larceny": "All Other Larceny",
    "animal-cruelty": "Animal Cruelty",
    "simple-assault": "Simple Assault",
    "rape": "Forcible Rape",
    "forgery": "Counterfeiting/Forgery",
    "weapons-violations": "Weapon Law Violations",
    "stolen-property": "Stolen Property Offenses",
    "pick-pocketing": "Pocket-picking",
    "burglary": "Burglary/Breaking & Entering",
    "arson": "Arson",
    "prostitution": "Prostitution",
    "forcible-sodomy": "Forcible Sodomy",
    "aggravated-assault": "Aggravated Assault",
    "robbery": "Robbery",
    "drug-violations": "Drug/Narcotic Violations"
}
