LOCATIONS = {
    "sullivans-island",
    "williamston",
    "ridgeville",
    "cottageville",
    "rock-hill",
    "west-union",
    "fort-mill",
    "cherokee",
    "johnsonville",
    "greenville",
    "charleston",
    "new-ellenton",
    "calhoun-falls",
    "fairfield",
    "nichols",
    "clarendon",
    "liberty",
    "summerton",
    "gifford",
    "st.-stephen",
    "chapin",
    "kingstree",
    "st.-george",
    "bamberg",
    "west-pelzer",
    "saluda",
    "bennettsville",
    "honea-path",
    "pickens",
    "lincolnville",
    "quinby",
    "union",
    "summerville",
    "port-royal",
    "gaffney",
    "due-west",
    "mccormick",
    "williston",
    "laurens",
    "bath",
    "timmonsville",
    "surfside-beach",
    "loris",
    "abbeville",
    "jonesville",
    "bluffton",
    "hardeeville",
    "dorchester",
    "darlington",
    "walterboro",
    "oconee",
    "holly-hill",
    "goose-creek",
    "dillon",
    "williamsburg",
    "denmark",
    "springfield",
    "inman",
    "bonneau",
    "pacolet",
    "manning",
    "mcbee",
    "lancaster",
    "latta",
    "tega-cay",
    "jasper",
    "travelers-rest",
    "tigerville",
    "greenwood",
    "westminster",
    "estill",
    "aiken",
    "ninety-six",
    "trenton",
    "richland",
    "society-hill",
    "jamestown",
    "aynor",
    "hemingway",
    "moncks-corner",
    "santee",
    "harleyville",
    "hanahan",
    "scranton",
    "bethune",
    "north-charleston",
    "edisto-beach",
    "bowman",
    "columbia",
    "beaufort",
    "clover",
    "belton",
    "seneca",
    "pageland",
    "woodruff",
    "hartsville",
    "pawleys-island",
    "varnville",
    "cheraw",
    "blacksburg",
    "north-myrtle-beach",
    "jackson",
    "sumter",
    "kershaw",
    "barnwell",
    "greeleyville",
    "olanta",
    "campobello",
    "camden",
    "salem",
    "lee",
    "fairfax",
    "yemassee",
    "horry",
    "olar",
    "ridge-spring",
    "pelion",
    "turbeville",
    "norway",
    "prosperity",
    "colleton",
    "branchville",
    "orangeburg",
    "gaston",
    "florence",
    "pamplico",
    "eutawville",
    "marion",
    "great-falls",
    "st.-matthews",
    "duncan",
    "allendale",
    "greer",
    "marlboro",
    "walhalla",
    "conway",
    "blythewood",
    "elloree",
    "easley",
    "irmo",
    "isle-of-palms",
    "lake-city",
    "clemson",
    "ware-shoals",
    "folly-beach",
    "johnston",
    "lake-view",
    "york",
    "coward",
    "wellford",
    "spartanburg",
    "anderson",
    "mccoll",
    "andrews",
    "winnsboro",
    "berkeley",
    "batesburg-leesville",
    "whitmire",
    "cayce",
    "blackville",
    "central",
    "springdale",
    "ridgeland",
    "clio",
    "west-columbia",
    "lexington",
    "landrum",
    "north-augusta",
    "mount-pleasant",
    "newberry",
    "clinton",
    "calhoun",
    "chesterfield",
    "perry",
    "fort-lawn",
    "cowpens",
    "chesnee",
    "hampton",
    "simpsonville",
    "lane",
    "edgefield",
    "bishopville",
    "cameron",
    "pendleton",
    "wagener",
    "chester",
    "fountain-inn",
    "ehrhardt",
    "north",
    "georgetown",
    "elgin",
    "myrtle-beach",
    "lamar",
    "mauldin",
    "mullins",
    "salley",
    "lyman",
    "swansea"
}
COUNTIES = {
    "abbeville",
    "aiken",
    "allendale",
    "anderson",
    "bamberg",
    "barnwell",
    "beaufort",
    "berkeley",
    "calhoun",
    "charleston",
    "cherokee",
    "chester",
    "chesterfield",
    "clarendon",
    "colleton",
    "darlington",
    "dillon",
    "dorchester",
    "edgefield",
    "fairfield",
    "florence",
    "georgetown",
    "greenville",
    "greenwood",
    "hampton",
    "horry",
    "jasper",
    "kershaw",
    "lancaster",
    "laurens",
    "lee",
    "lexington",
    "marion",
    "marlboro",
    "mcCormick",
    "newberry",
    "oconee",
    "orangeburg",
    "pickens",
    "richland",
    "saluda",
    "spartanburg",
    "sumter",
    "union",
    "williamsburg",
    "york"
}

YEARS = {
    1990,
    1991,
    1992,
    1993,
    1994,
    1995,
    1996,
    1997,
    1998,
    1999,
    2000,
    2002,
    2003,
    2004,
    2005,
    2006,
    2007,
    2008,
    2009,
    2010,
    2011,
    2012,
    2013,
    2014,
    2015,
    2016,
    2017,
    2018,
    2019,
    2020,
    2021
}

CRIMES = {
    "all": "all",
    "aggravated-assault": "Aggravated Assault",
    "all-other-offenses-(except-traffic)": "All Other Offenses (Except Traffic)",
    "arson": "Arson",
    "burglary": "Burglary",
    "curfew-and-loitering-law-violations": "Curfew and Loitering Law Violations",
    "disorderly-conduct": "Disorderly Conduct",
    "driving-under-the-influence": "Driving Under the Influence",
    "drug-abuse-violations---grand-total": "Drug Abuse Violations - Grand Total",
    "drunkenness": "Drunkenness",
    "embezzlement": "Embezzlement",
    "forgery-and-counterfeiting": "Forgery and Counterfeiting",
    "fraud": "Fraud",
    "gambling---total": "Gambling - Total",
    "human-trafficking---commercial-sex-acts": "Human Trafficking - Commercial Sex Acts",
    "human-trafficking---involuntary-servitude": "Human Trafficking - Involuntary Servitude",
    "larceny---theft": "Larceny - Theft",
    "liquor-laws": "Liquor Laws",
    "manslaughter-by-negligence": "Manslaughter by Negligence",
    "motor-vehicle-theft": "Motor Vehicle Theft",
    "murder-and-nonnegligent-manslaughter": "Murder and Nonnegligent Manslaughter",
    "offenses-against-the-family-and-children": "Offenses Against the Family and Children",
    "prostitution-and-commercialized-vice": "Prostitution and Commercialized Vice",
    "rape": "Rape",
    "robbery": "Robbery",
    "sex-offenses-(except-rape--and-prostitution-and-commercialized-vice)": "Sex Offenses (Except Rape, and Prostitution and Commercialized Vice)",
    "simple-assault": "Simple Assault",
    "stolen-property:-buying--receiving--possessing": "Stolen Property: Buying, Receiving, Possessing",
    "suspicion": "Suspicion",
    "vagrancy": "Vagrancy",
    "vandalism": "Vandalism",
    "weapons:-carrying--possessing--etc.": "Weapons: Carrying, Possessing, Etc."
}
